version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "${BACKEND_PORT:-9999}:${BACKEND_PORT:-9999}"

    command: poetry run uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-9999}
